config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users

  resources :users

  resources :products do
    resources :comments
  end

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  root 'simple_pages#landing_page'

  post 'simple_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'

  resources :orders, only: [:index, :show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all?
    else
      can :manage, User, id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :body, presence: true
		validates :user, presence: true
		validates :product, presence: true
		validates :rating, numericality: { only_integer: true }
		
  belongs_to :user
  belongs_to :product

  scope :rating_desc, -> { order(rating: :desc) }
  scope :rating_asc, -> { order(rating: :asc) }

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true
	
	has_many :orders
	has_many :comments

	def self.search(search_term)
		Product.where("name LIKE ?", "%#{search_term}%")
	end

	def highest_rating_comment
		comments.rating_desc.first
	end

	def lowest_rating_comment
		comments.rating_asc.first
	end

	def average_rating
		comments.average(:rating).to_f
	end
	
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	has_many :orders
	has_many :comments

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@product = Product.find(params[:product_id])
		@comment = @product.comments.new(comment_params)
		@comment.user = current_user
		respond_to do |format|
			if @comment.save
				ActionCable.server.broadcast 'product_channel', comment: @comment, agerage_rating: @comment.product.average_rating
				format.html { redirect_to @product, notice: 'Review was created successfully.' }
				format.json { render :show, status: :created, location: @product }
				format.js
			else
				format.html { redirect_to @product, notice: 'Review was not saved successfully' }
				format.json { render json: @comment.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		product = @comment.product
		@comment.destroy
		redirect_to product
	end

	private

	def comment_params
		params.require(:comment).permit(:user_id, :body, :rating)
	end

end

app/controllers/orders_controllers.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!

	def index
		@orders = Order.include(:product).all
	end

	def show
	end

	def new
	end

	def create
	end

	def destroy
	end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count                  = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="footer, links, icons" />

    <title>Nameofapp</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'ratyrate.js', "data-turbolinks-track" => false %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

  </head>

  <body>

    <% if notice %>
      <div id="notice" class="alert alert-warning" role="alert"><%= notice %></div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger" role="alert"><%= alert %></div>
    <% end %>

  	<nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">gearDventures</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'About', simple_pages_about_path %></li>
            <li><%= link_to 'Contact', simple_pages_contact_path %></li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li>
              <% if user_signed_in? %>
                  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
                <% else %>
                  <%= link_to('Login', new_user_session_path) %>
                <% end %>
            </li>
          </ul>
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
                <%= form.label :q, 'Search for:', class:"hidden" %>
                <%= form.text_field :q, id: 'q', value: params[:q], class:"form-control", placeholder:"Search Term" %>
                <%= form.submit 'Search', class:"btn btn-default" %>
              <% end %>
            </div>
          </form>
        </div>
      </div>
  	</nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <footer class="footer-distributed">
      <div class="footer-right">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>
      </div>

      <div class="footer-left">
        <p class="footer-links">
          <a><%= link_to 'Home', simple_pages_index_path %></a>
          ·
          <a><%= link_to 'Products', products_path %></a>
          ·
          <a><%= link_to 'About', simple_pages_about_path %></a>
          ·
          <a><%= link_to 'Contact', simple_pages_contact_path %></a>
        </p><br>
        <p>gearDventure &copy;<%= Date.today.year %></p>
      </div>
    </footer>

  </body>
</html>

app/views/shared/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="<%= @product.image_url %>"
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %>"
  data-amount="<%= @product.price*100 %>">
</script>

<%= hidden_field_tag(:product_id, @product.id) %>